{
 "title": "So1s Billing Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "cpu_cost_per_hour", "query": "0.05" },
   { "name": "memory_cost_per_hour", "query": "0.01" },
   { "name": "gpu_cost_per_hour", "query": "0.42" },
   { "name": "margin", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\"}[$__range])) * $cpu_cost_per_hour) + (sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\"}[$__range])) / 1073741824 * $memory_cost_per_hour) + (sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\"}[$__range])) / 100 * $gpu_cost_per_hour)* $margin",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\"}[$__range])) * $cpu_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "Memory Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\"}[$__range])) / 1073741824 * $memory_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "GPU Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\"}[$__range])) / 100 * $gpu_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "Total Cost by Workload",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time (\nnode_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\"}[$__range]\n    )\n     * on(namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$user\", workload_type=\"deployment\"} * $cpu_cost_per_hour)) + (sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\"}[$__range]) * on(namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$user\", workload_type=\"deployment\"} / 1073741824 * $memory_cost_per_hour)) * $margin"
    },
    {
     "expr": "(sum(sum_over_time (\nnode_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\"}[$__range]\n    )\n     * on(namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$user\", workload_type=\"job\"} * $cpu_cost_per_hour)) + (sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\"}[$__range]) * on(namespace, pod) group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$user\", workload_type=\"job\"} / 1073741824 * $memory_cost_per_hour)) * $margin"
    }
   ]
  },
  {
   "title": "Total Cost by Resource",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\"}[$__range])) * $cpu_cost_per_hour * $margin"
    },
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\"}[$__range])) / 1073741824 * $memory_cost_per_hour * $margin"
    },
    {
     "expr": "sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\"}[$__range])) / 100 * $gpu_cost_per_hour * $margin"
    }
   ]
  },
  { "title": "Inference Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Inference Server Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod!~\"build.*\"}[$__range])) * $cpu_cost_per_hour) + (sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod!~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour) + (sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\", pod!~\"build.*\"}[$__range])) / 100 * $gpu_cost_per_hour)* $margin"
    }
   ]
  },
  {
   "title": "CPU Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod!~\"build.*\"}[$__range])) * $cpu_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "Memory Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod!~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "GPU Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\", pod!~\"build.*\"}[$__range])) / 100 * $gpu_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "Cost by resource",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod!~\"build.*\"}[$__range])) * $cpu_cost_per_hour) + (sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod!~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour) * $margin"
    },
    {
     "expr": "sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod!~\"build.*\"}[$__range])) * $cpu_cost_per_hour * $margin"
    },
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod!~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour * $margin"
    },
    {
     "expr": "sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\", pod!~\"build.*\"}[$__range])) / 100 * $gpu_cost_per_hour * $margin"
    }
   ]
  },
  { "title": "Builder Billing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Model Builder Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod=~\"build.*\"}[$__range])) * $cpu_cost_per_hour) + (sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod=~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour) + (sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\", pod=~\"build.*\"}[$__range])) * $gpu_cost_per_hour) * $margin"
    }
   ]
  },
  {
   "title": "CPU Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod=~\"build.*\"}[$__range])) * $cpu_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "Memory Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod=~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "GPU Total Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\", pod=~\"build.*\"}[$__range])) / 100 * $gpu_cost_per_hour * $margin"
    }
   ]
  },
  {
   "title": "Cost by resource",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod=~\"build.*\"}[$__range])) * $cpu_cost_per_hour) + (sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod=~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour) * $margin"
    },
    {
     "expr": "sum(sum_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$user\", pod=~\"build.*\"}[$__range])) * $cpu_cost_per_hour * $margin"
    },
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$user\",container!=\"\", image!=\"\", pod=~\"build.*\"}[$__range])) / 1073741824 * $memory_cost_per_hour * $margin"
    },
    {
     "expr": "sum(sum_over_time(DCGM_FI_DEV_GPU_UTIL{namespace=\"$user\", pod=~\"build.*\"}[$__range])) / 100 * $gpu_cost_per_hour * $margin"
    }
   ]
  }
 ]
}