{
 "title": "Inference / Inference Servers",
 "tags": [
  "So1s",
  "Inference"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Inference Servers Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| filter kubernetes.container_name like /inference-/",
     "logGroupNames": [
      "/aws/containerinsights/So1s/inference"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Input Records Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{name=\"inference\"}[5m]))"
    }
   ]
  },
  {
   "title": "Output Record Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{name=\"inference\"}[5m]))"
    }
   ]
  },
  {
   "title": "Input Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{name=\"inference\"}[5m]))"
    }
   ]
  },
  {
   "title": "Output Bytes Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{name=\"inference\"}[5m]))"
    }
   ]
  },
  {
   "title": "Output Retry/Failed Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{name=\"inference\"}[1m]))"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{name=\"inference\"}[1m]))"
    }
   ]
  },
  {
   "title": "Output Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{name=\"inference\"}[1m]))"
    }
   ]
  }
 ]
}