{
 "title": "SLI / SLO dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Builder Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"so1s-so1s\", pod=~\"build-.*\"}) / count(kube_pod_container_status_waiting{namespace=\"so1s-so1s\", pod=~\"build-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"so1s-so1s\", pod=~\"build-.*\"}) / count(kube_pod_container_status_running{namespace=\"so1s-so1s\", pod=~\"build-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"so1s-so1s\", pod=~\"build-.*\"}) / count(kube_pod_container_status_terminated{namespace=\"so1s-so1s\", pod=~\"build-.*\"})"
    }
   ]
  },
  {
   "title": "Builder Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"so1s-so1s\", pod=~\"build-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"so1s-so1s\", pod=~\"build-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"so1s-so1s\", pod=~\"build-.*\"})"
    }
   ]
  },
  {
   "title": "Inference Server Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"so1s-so1s\", pod=~\"inference-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"so1s-so1s\", pod=~\"inference-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"so1s-so1s\", pod=~\"inference-.*\"})"
    }
   ]
  },
  {
   "title": "Inference Server Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"so1s-so1s\", pod=~\"inference-.*\"}) / count(kube_pod_container_status_waiting{namespace=\"so1s-so1s\", pod=~\"inference-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"so1s-so1s\", pod=~\"inference-.*\"}) / count(kube_pod_container_status_running{namespace=\"so1s-so1s\", pod=~\"inference-.*\"})"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"so1s-so1s\", pod=~\"inference-.*\"}) / count(kube_pod_container_status_terminated{namespace=\"so1s-so1s\", pod=~\"inference-.*\"})"
    }
   ]
  }
 ]
}