apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: so1s-project-dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
spec:
  # Project description
  description: The app bundle So1s project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: "*"
      server: "*"

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
